name: codelapse
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

isar_version: &isar_version 3.0.5 # define the version to be used

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  isar: *isar_version
  isar_flutter_libs: *isar_version
  equatable:
  dartz: ^0.10.1
  flutter_hooks: ^0.18.6
  dotted_border: 2.0.0+3
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.0
  replay_bloc: ^0.2.3 
  path_provider: ^2.0.14
  tuple: ^2.0.1 # remove? 
  sandbox_logger:
  uuid: ^3.0.7 
  watcher: ^1.0.2
  flutter_lints: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version  
  build_runner: ^2.3.3
  freezed: ^2.3.2
  
flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
